import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { makeFakeClaudeDir, userLine, type FakeClaudeDir } from './testing/claude-dir.ts';
import { claudeDirFromEnv, WorkContextCollector, type CollectBudget } from './work-context/collector.ts';
import { maskSecrets, MASK } from './work-context/secrets.ts';
import { isPastedBlob } from './work-context/session-reader.ts';
import { DEFAULT_SWEEP_SKIP, sweepSkipFromEnv, SweepSkipList } from './work-context/skip-list.ts';

const NOW = new Date('2026-09-28T09:00:00Z');
const RECENT = new Date('2026-09-27T12:00:00Z');
const OLD = new Date('2026-09-10T12:00:00Z');
const BIG: CollectBudget = { claudeMd: 20_000, sessions: 20_000, memory: 20_000 };

let fake: FakeClaudeDir;

beforeEach(() => {
  fake = makeFakeClaudeDir();
});

afterEach(() => {
  fake.remove();
});

function collector(budget: CollectBudget = BIG, log?: (message: string) => void): WorkContextCollector {
  return new WorkContextCollector({ claudeDir: fake.claudeDir, home: fake.home, now: NOW, budget, log });
}

/** A realistic session: noise Claude Code writes into the user turn, then what the user typed. */
function busySession(): unknown[] {
  return [
    { type: 'permission-mode', permissionMode: 'auto', sessionId: 'a' },
    userLine('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>', '2026-09-27T10:00:00.000Z', { isMeta: true }),
    userLine('<command-name>/effort</command-name>', '2026-09-27T10:00:01.000Z'),
    userLine('<system-reminder>\nToday is Sunday.\n</system-reminder>\nMove the Depot runners to the new pool, then check CI cost', '2026-09-27T10:01:00.000Z'),
    { type: 'assistant', message: { content: [{ type: 'tool_use', id: 't1', name: 'Bash' }] }, timestamp: '2026-09-27T10:01:30.000Z' },
    userLine([{ type: 'tool_result', tool_use_id: 't1', content: 'SECRET TOOL OUTPUT '.repeat(500) }], '2026-09-27T10:02:00.000Z', { toolUseResult: {} }),
    userLine('{"level":"error","msg":"pool exhausted","trace":"..."}\n{"level":"error"}', '2026-09-27T10:03:00.000Z'),
    userLine('A task notification', '2026-09-27T10:03:30.000Z', { origin: { kind: 'task-notification' }, promptSource: 'system' }),
    userLine(`why is ${'the queue slow '.repeat(40)}`, '2026-09-27T10:04:00.000Z'),
    userLine('use token ghp_abcdefghijklmnopqrstuvwxyz0123456789 for the API', '2026-09-27T10:05:00.000Z'),
    userLine('a fourth prompt that is not kept', '2026-09-27T10:06:00.000Z'),
    { type: 'ai-title', aiTitle: 'Depot runner pool', sessionId: 'a' },
    userLine('This session is being continued from a previous conversation.\n\nSummary:\n1. Depot pool move, waiting on #4521 review.', '2026-09-27T11:00:00.000Z', {
      isCompactSummary: true,
      origin: undefined,
      promptSource: undefined,
    }),
    { type: 'assistant', message: { content: [{ type: 'text', text: 'done' }] }, timestamp: '2026-09-27T11:30:00.000Z' },
  ];
}

describe('WorkContextCollector', () => {
  it('reads CLAUDE.md and follows @-includes under ~/.claude and its dotfiles only', async () => {
    fake.write('dotfiles/claude/CLAUDE.md', '# Julian\nI work on DevEx.\n@RTK.md\n@~/secret-notes.md\nmail jane@example.com\n```\n@example.md\n```\n');
    fake.write('dotfiles/claude/RTK.md', 'RTK is a CLI proxy.\n@nested.md');
    fake.write('dotfiles/claude/nested.md', 'Nested include.');
    fake.write('dotfiles/claude/example.md', 'Never read: inside a code fence.');
    fake.write('secret-notes.md', 'Never read: outside the allowed folders.');
    fake.link('.claude/CLAUDE.md', `${fake.home}/dotfiles/claude/CLAUDE.md`);

    const { items, stats } = await collector().collect();

    expect(items.filter((item) => item.kind === 'claude_md').map((item) => [item.id, item.ref])).toEqual([
      ['c1', '~/.claude/CLAUDE.md'],
      ['c2', '~/dotfiles/claude/RTK.md'],
      ['c3', '~/dotfiles/claude/nested.md'],
    ]);
    expect(items.map((item) => item.text).join('\n')).not.toContain('Never read');
    expect(stats.claudeMdFiles).toBe(3);
  });

  it('takes memory indexes first, with the project folder in the ref', async () => {
    fake.write('.claude/projects/-Users-me-workspace-posthog/memory/MEMORY.md', '- [Depot](depot.md) CI move', OLD);
    fake.write('.claude/projects/-Users-me-workspace-posthog/memory/depot.md', 'Depot move notes', RECENT);
    fake.write('.claude/projects/-Users-me-workspace-posthog/memory/old.md', 'Old notes', OLD);
    fake.write('.claude/projects/-Users-me-workspace-hobby/memory/notes.txt', 'not markdown', RECENT);

    const { items, stats } = await collector().collect();

    expect(items.map((item) => item.ref)).toEqual([
      '~/.claude/projects/-Users-me-workspace-posthog/memory/MEMORY.md',
      '~/.claude/projects/-Users-me-workspace-posthog/memory/depot.md',
      '~/.claude/projects/-Users-me-workspace-posthog/memory/old.md',
    ]);
    expect(stats.memoryFiles).toBe(3);
  });

  it('keeps only light signals from recent sessions and skips tool results, noise and pasted blobs', async () => {
    fake.session('-Users-me-workspace-posthog', 'a', busySession(), RECENT);
    fake.session('-Users-me-workspace-posthog', 'old', [userLine('last month', '2026-09-10T10:00:00.000Z')], OLD);
    fake.session('-Users-me-workspace-posthog', 'sdk', [userLine('prompt from a program', '2026-09-27T09:00:00.000Z', { entrypoint: 'sdk-cli' })], RECENT);

    const { items, stats, lastSeenAt } = await collector().collect();

    expect(items).toHaveLength(1);
    const session = items[0]!;
    expect(session.id).toBe('s1');
    expect(session.kind).toBe('session');
    expect(session.ref).toMatch(/^posthog · 2026-09-2\d \d\d:\d\d · "Depot runner pool"$/);
    const prompts = session.text.split('\n').filter((line) => line.startsWith('- '));
    expect(prompts).toHaveLength(3);
    expect(prompts[0]).toBe('- Move the Depot runners to the new pool, then check CI cost');
    expect(prompts[1]!.length).toBeLessThanOrEqual(302);
    expect(prompts[1]!.endsWith('…')).toBe(true);
    expect(prompts[2]).toBe(`- use token ${MASK} for the API`);
    expect(session.text).toContain('Compaction summary: 1. Depot pool move, waiting on #4521 review.');
    for (const noise of ['SECRET TOOL OUTPUT', 'Caveat', '/effort', 'Today is Sunday', 'pool exhausted', 'task notification', 'fourth prompt', 'last month', 'program']) {
      expect(session.text).not.toContain(noise);
    }
    expect(stats).toMatchObject({ sessions: 1, sessionFilesScanned: 2, maskedSecrets: 1 });
    expect(stats.dropped).toContainEqual(expect.objectContaining({ kind: 'session', reason: 'started by a program (SDK)' }));
    expect(lastSeenAt).toBe('2026-09-27T11:30:00.000Z');
  });

  it('keeps the newest of forked sessions that repeat the same prompts', async () => {
    const lines = [userLine('drive the runner image bump', '2026-09-25T10:00:00.000Z')];
    fake.session('-Users-me-workspace-example-infra', 'parent', lines, RECENT);
    fake.session('-Users-me-workspace-example-infra', 'fork', [...lines, userLine('later', '2026-09-26T10:00:00.000Z', { isMeta: true })], RECENT);

    const { items, stats } = await collector().collect();

    expect(items).toHaveLength(1);
    expect(stats.dropped).toContainEqual(expect.objectContaining({ reason: 'same prompts as a newer session (fork)' }));
  });

  it('cuts to the budget, newest sessions first, and logs what it dropped', async () => {
    for (let day = 20; day <= 27; day++) {
      fake.session('-Users-me-workspace-posthog', `s${day}`, [userLine(`work on day ${day} ${'x'.repeat(200)}`, `2026-09-${day}T10:00:00.000Z`)], RECENT);
    }
    fake.write('.claude/projects/p/memory/MEMORY.md', 'm'.repeat(2000), RECENT);
    const logs: string[] = [];

    const { items, stats } = await collector({ claudeMd: 0, sessions: 1000, memory: 500 }, (line) => logs.push(line)).collect();

    const days = items.map((item) => /work on day (\d+)/.exec(item.text)?.[1]);
    expect(days).toEqual(['27', '26', '25']);
    expect(stats.sentChars).toBeLessThanOrEqual(1500);
    expect(stats.budgetChars).toBe(1500);
    expect(stats.droppedCount).toBe(6);
    expect(logs).toEqual(['work context: dropped 5 (session: over budget)', 'work context: dropped 1 (memory: over budget)']);
  });

  it('never reads project folders on the skip list, memory or sessions, and counts them', async () => {
    fake.write('.claude/projects/-Users-me-workspace-posthog/memory/MEMORY.md', 'posthog work', RECENT);
    fake.write('.claude/projects/-Users-me-workspace-taxes/memory/MEMORY.md', 'PRIVATE money notes', RECENT);
    fake.write('.claude/projects/-Users-me-workspace-my-blog-com/memory/MEMORY.md', 'PRIVATE site notes', RECENT);
    fake.session('-Users-me-workspace-garden-nas', 'h', [userLine('PRIVATE nas prompt', '2026-09-27T10:00:00.000Z')], RECENT);
    fake.session('-Users-me-workspace-posthog', 'p', [userLine('posthog prompt', '2026-09-27T10:00:00.000Z')], RECENT);
    const logs: string[] = [];

    const { items, stats } = await new WorkContextCollector({
      claudeDir: fake.claudeDir,
      home: fake.home,
      now: NOW,
      budget: BIG,
      skipList: new SweepSkipList(DEFAULT_SWEEP_SKIP),
      log: (message) => logs.push(message),
    }).collect();

    expect(items.map((item) => item.text).join('\n')).not.toContain('PRIVATE');
    expect(items).toHaveLength(2);
    expect(stats).toMatchObject({ skippedProjects: 3, skipPatterns: DEFAULT_SWEEP_SKIP, sessionFilesScanned: 1 });
    expect(JSON.stringify(stats.dropped)).not.toContain('workspace-taxes');
    expect(logs).toContain('work context: skipped 3 project folders (skip list)');
  });

  it('works on an empty or missing folder', async () => {
    const empty = new WorkContextCollector({ claudeDir: '/nonexistent/claude', now: NOW });
    expect(await empty.collect()).toMatchObject({ items: [], lastSeenAt: null, stats: { sentChars: 0, droppedCount: 0 } });
  });
});

describe('sweep skip list', () => {
  it('matches the pattern as a run of whole tokens in the folder name', () => {
    const list = new SweepSkipList(['taxes', 'hobby', 'my-blog-com']);
    expect(list.skips('-Users-me-workspace-taxes')).toBe(true);
    expect(list.skips('-Users-me-workspace-hobby')).toBe(true);
    expect(list.skips('-Users-me-workspace-my-blog-com')).toBe(true);
    expect(list.skips('-Users-me-workspace-posthog')).toBe(false);
    expect(list.skips('-Users-me-workspace-ghatchup')).toBe(false);
    expect(list.skips('-Users-me')).toBe(false);
  });

  it('matches names that go on after the pattern, and punctuation or case never count', () => {
    const list = new SweepSkipList(['Taxes', 'hobby', 'my-blog.com']);
    expect(list.skips('-Users-me-workspace-taxes-tools')).toBe(true);
    expect(list.skips('-Users-me-workspace-hobby-notes')).toBe(true);
    expect(list.skips('-Users-me-workspace-my-blog-com-v2')).toBe(true);
  });

  it('needs whole tokens: a pattern never matches part of a token', () => {
    const list = new SweepSkipList(['hobby', 'my-blog-com']);
    expect(list.skips('-Users-me-workspace-hass')).toBe(false);
    expect(list.skips('-Users-me-workspace-sha-tools')).toBe(false);
    expect(list.skips('-Users-me-workspace-my-blog')).toBe(false);
    expect(list.skips('-Users-me-workspace-my-blog-org')).toBe(false);
  });

  it('errs on the side of skipping when the pattern sits in a parent folder or mid-name', () => {
    // Without the disk the folder cannot be split into path segments, and
    // over-skipping only loses context.
    const list = new SweepSkipList(['hobby', 'taxes']);
    expect(list.skips('-Users-me-workspace-posthog-hobby-x')).toBe(true);
    expect(list.skips('-Users-me-taxes-archive-2024')).toBe(true);
  });

  it('takes POSTPILE_SWEEP_SKIP over the defaults, empty means skip nothing', () => {
    expect(sweepSkipFromEnv(undefined)).toEqual(['taxes', 'garden', 'hobby', 'my-blog-com']);
    expect(sweepSkipFromEnv(' taxes , taxes,,')).toEqual(['taxes', 'taxes']);
    expect(sweepSkipFromEnv('')).toEqual([]);
    expect(new SweepSkipList([]).skips('-Users-me-workspace-taxes')).toBe(false);
  });
});

describe('claudeDirFromEnv', () => {
  it('defaults to ~/.claude and takes POSTPILE_CLAUDE_DIR', () => {
    expect(claudeDirFromEnv({}, '/home/j')).toBe('/home/j/.claude');
    expect(claudeDirFromEnv({ POSTPILE_CLAUDE_DIR: '/tmp/fake' }, '/home/j')).toBe('/tmp/fake');
  });
});

describe('maskSecrets', () => {
  it('masks tokens, keys, passwords and URL credentials', () => {
    const text = [
      'gh: ghp_abcdefghijklmnopqrstuvwxyz0123456789',
      'anthropic sk-ant-api03-abcdefghijklmnopqrstuvwxyz',
      'aws AKIAABCDEFGHIJKLMNOP',
      'slack xoxb-1234567890-abcdefghij',
      'posthog phx_abcdefghijklmnopqrstuvwxyz12',
      'password: hunter2hunter2',
      'API_KEY=abc123def456',
      'curl -H "Authorization: Bearer abcdefghijklmnopqrstuvwx"',
      'postgres://admin:s3cret@db.internal:5432/app',
      '-----BEGIN RSA PRIVATE KEY-----\nMIIEow\n-----END RSA PRIVATE KEY-----',
    ].join('\n');

    const result = maskSecrets(text);

    for (const secret of ['ghp_abc', 'sk-ant', 'AKIAABC', 'xoxb-', 'phx_abc', 'hunter2', 'abc123def456', 'abcdefghijklmnopqrstuvwx"', 's3cret', 'MIIEow']) {
      expect(result.text).not.toContain(secret);
    }
    expect(result.text).toContain('password: [masked]');
    expect(result.text).toContain('API_KEY=[masked]');
    expect(result.text).toContain('Bearer [masked]');
    expect(result.text).toContain('postgres://[masked]@db.internal');
    expect(result.count).toBe(10);
  });

  it('leaves ordinary text and placeholders alone', () => {
    const text = 'Set the token to <your token> and read tokens.md; PR #4521 by @viewer.\ntoken: $GITHUB_TOKEN';
    expect(maskSecrets(text)).toEqual({ text, count: 0 });
  });
});

describe('isPastedBlob', () => {
  it('spots pasted JSON, logs and stack traces but not typed prose', () => {
    expect(isPastedBlob('{"a": 1}')).toBe(true);
    expect(isPastedBlob('2026-09-27T10:00:00Z ERROR pool exhausted')).toBe(true);
    expect(isPastedBlob('Traceback (most recent call last):\n  File "x.py"')).toBe(true);
    expect(isPastedBlob(Array.from({ length: 30 }, (_, i) => `k${i}=v${i}`).join('\n'))).toBe(true);
    expect(isPastedBlob('check 106448 merged a materialized view, does it work already?')).toBe(false);
  });
});
