import type { Comment } from './types.ts';

// Bots account for well over half of all @-mentions in a busy repo: CI nags,
// merge-queue chatter, review bots. List carried over from ghatchup.
const botLogin =
  /(\[bot\]$|^github-actions$|^trunk-io$|^posthog$|^stamphog$|^codecov|^sonarcloud|^dependabot|^mendral-app$|^copilot|^greptile|^inkeep|^veria-ai$|^renovate|^snyk|^netlify|^vercel$|^chatgpt-codex|^coderabbit|^graphite-app$|^parameterai$|-posthog$|-bot$)/i;

// Automation posting through a human account says so in the body. Taking it at
// its word is more reliable than guessing from the author.
const botBody =
  /(not written by a human|automated comment|this is an automated|generated by .{0,30}bot|<!-- *bot)/i;

/**
 * The one rule for "is this automation". GitHub App accounts come in as
 * "name[bot]" (the GraphQL reader adds the suffix for __typename Bot, see
 * `actorLogin`), and the list above catches automation on user accounts.
 * The renderer does not import this: it gets what it needs as data (for
 * example `PrStatus.agentApprovers`) and only checks the [bot] suffix for
 * avatars, which have no public URL for app accounts.
 */
export function isBot(login: string): boolean {
  return login === '' || botLogin.test(login);
}

export function isMachineComment(comment: Pick<Comment, 'author' | 'body'>): boolean {
  return isBot(comment.author) || botBody.test(comment.body);
}
