// Every query key in one place, so actions can invalidate what they change.
export const queryKeys = {
  config: ['config'] as const,
  githubWrites: ['github-writes'] as const,
  live: ['live'] as const,
  tools: ['tools'] as const,
  update: ['update'] as const,
  mcpConnection: ['mcp-connection'] as const,
  lastSync: ['last-sync'] as const,
  syncProgress: ['sync-progress'] as const,
  topics: ['topics'] as const,
  finishedTopics: ['finished-topics'] as const,
  viewer: ['viewer'] as const,
  teamRoles: ['team-roles'] as const,
  repos: ['repos'] as const,
  inboxCleanup: ['inbox-cleanup'] as const,
  topic: (topicId: string) => ['topic', topicId] as const,
  /** Every topic's open lessons share the prefix, so a teach can refresh them all. */
  lessonsAll: ['lessons'] as const,
  lessons: (topicId: string) => ['lessons', topicId] as const,
  search: (query: string) => ['search', query] as const,
  pr: (prKey: string) => ['pr', prKey] as const,
  chat: (tileId: string) => ['chat', tileId] as const,
  proposals: ['proposals'] as const,
  instructions: ['instructions'] as const,
  instructionsChat: ['instructions-chat'] as const,
  workContext: ['work-context'] as const,
  setupStatus: ['setup-status'] as const,
  setupChecks: ['setup-checks'] as const,
  setupSweep: ['setup-sweep'] as const,
  debugNotifications: (limit: number) => ['debug-notifications', limit] as const,
  handledQuietly: ['handled-quietly'] as const,
  memorySources: (targetKey: string) => ['memory-sources', targetKey] as const,
};
